name: 🔄 Update README

on:
  push:
    branches: ["master"]
    
  workflow_dispatch:

jobs:
  checkout: 
    name: "Checkout Code"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

  build:
    name: "Build Templates"
    runs-on: ubuntu-latest
    needs: [checkout]
    container:
      image: mcr.microsoft.com/playwright:latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: '>=20'

      - name: Increment version
        run: npm version patch --prefix ./src

      - name: Install Dependencies
        run: npm ci --prefix ./src

      - name: Test Project
        run: npm run test --prefix ./src
        env:
          HOME: /root

      - name: Build Project
        run: npm run build --prefix ./src

      - name: Copy build output
        run: cp -r src/out/* .

  Commit:
    name: "Commit Changes"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Commit Changes
        run: |
          ls -lah
          git config --local ./ user.email "${{secrets.GIT_EMAIL}}"
          git config --local ./ user.name "${{secrets.GIT_NAME}}"
          git add .
          git commit -m "Update README" || echo "No changes to commit"
          git push
