name: 📷 Update Snapshots

on:
  push:
    branches: ["master"]
    paths:
      - '.github/workflows/update-snapshots.yml'

  workflow_dispatch:

jobs:
  update-snapshot:
    name: "Update Snapshots and Commit"
    runs-on: ubuntu-latest
    env:
      github: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
    
      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: '>=20'
          cache: 'npm'
          cache-dependency-path: "${{ github.workspace }}/src"
          
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
        
      - name: Node Cache
        uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: |
             ${{ steps.npm-cache-dir.outputs.dir }}
             ${{ github.workspace }}/src/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('${{ github.workspace }}/src/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci --prefix ./src
        
      - name: Install Playwright Browsers
        run: npm exec --prefix ./src playwright install -- --with-deps

      - name: Update Snapshots
        run: npm run update-snapshots --prefix ./src

      - name: Commit Changes
        run: |
          git config --global --add safe.directory $(pwd)
          git status .
          git config user.email "${{secrets.GIT_EMAIL}}"
          git config user.name "${{secrets.GIT_NAME}}"
          git add .
          git commit -m "Update Snapshots" || echo "No changes to commit"
          git push
