name: 📷 Update Snapshots

on:
  push:
    branches: ["master"]
    paths:
      - '.github/workflows/update-snapshots.yml'

  workflow_dispatch:

jobs:
  read-playwright-version:
    name: 'Read Playwright Version'
    runs-on: ubuntu-latest
    outputs:
      playwright-version: ${{ steps.get_playwright_version.outputs.playwright-version }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          playwright_version=$(node -e 'console.log(require("./src/package-lock.json")["packages"]["node_modules/@playwright/test"].version)')
          echo "playwright-version=$playwright_version" >> $GITHUB_OUTPUT
        id: get_playwright_version

  update-snapshot:
    name: "Update Snapshots and Commit"
    runs-on: ubuntu-latest
    needs: read-playwright-version
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.read-playwright-version.outputs.playwright-version }}-noble
      options: --user root
    env:
      HOME: /root
    steps:
      - name: Install Node Dependencies
        run: npm ci --prefix ./src

      - name: Update Snapshots
        env:
          github: true
        run: npm run update-snapshots --prefix ./src

      - name: Commit Changes
        run: |
          git config --global --add safe.directory $(pwd)
          git status .
          git config user.email "${{secrets.GIT_EMAIL}}"
          git config user.name "${{secrets.GIT_NAME}}"
          git add .
          git commit -m "Update Snapshots" || echo "No changes to commit"
          git push
